# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    env:
      version: 1.0.${{ github.run_number }}
      patchVersion: ${{ github.run_number }}
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      - uses: actions/setup-java@v3
        with:
          distribution: 'corretto' # See 'Supported distributions' for available options
          java-version: '11'

      # could also use gradle wrapper task https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-java-with-gradle
      - name: Build extension
        run: |
          chmod +x gradlew
          ./gradlew clean build -PBUILD_NUMBER=${{ env.patchVersion }} -PBUILD_SOURCEBRANCH=$GITHUB_REF_NAME -PBUILD_SOURCEVERSION=$GITHUB_SHA -PPACKAGE_VERSION=${{ env.version }}

      - name: Archive production artifacts
        uses: actions/upload-artifact@v3
        with:
          name: HTMLHeaderWidget-v${{ env.version }}
          path: build/distributions/*.zip
          retention-days: 1
